gpt tools, verify completions
Taycode/match-monorepo pull request #5
Opened 2024-04-07 13:43 UTC by TaslimOwolarafe

### Case 1:  `Single Skill`
>>> import os
>>> os.environ.setdefault("DJANGO_SETTINGS_MODULE", "server.match.settings")
'server.match.settings'
>>> 'server.match.settings'
'server.match.settings'
>>> from server.openai_client.client import OpenAPIClient
WARNING:root:No DATABASE_URL environment variable set, and so no databases setup
>>>
>>> key={key}
>>>
>>> message="Python Backend Engineer with 6 to 20 years experience"
>>> client=OpenAPIClient.query
>>> client(message=message, api_key=key)
#### '{"role":"Python Backend Engineer","skills":["Python"],"years_of_experience":{"gte":6,"lte":20}}'
>>> exit()

### Case 2: `Multiple Skills`
>>> message="Python, JS, TS, LangChain Backend Engineer with 6 to 20 years experience" 
>>> client(message=message, api_key=key)
[{'id': 'call_HXBLh64H9s9NqVLnaXqwv2zH', 'function': {'arguments': '{"role":"Backend Engineer","skills":["Python","JS","TS","LangChain"],"years_of_experience":{"gte":6,"lte":20}}', 'name': 'return_structured_job_search_query'}, 'type': 'function'}]
>>> y=client(message=message, api_key=key) 
>>> y.function
>>> y[0]['function']['arguments']  
#### '{"role":"Backend Engineer","skills":["Python","JS","TS","LangChain"],"years_of_experience":{"gte":6,"lte":20}}'

2024-04-12 21:23 UTC, Taycode requested changes

2024-04-12 21:23 UTC, Taycode commented on server/openai_client/client.py
> +                            #  "schema": SearchFields.model_json_schema()
can you please remove this comment ??

2024-04-12 21:23 UTC, Taycode commented on server/openai_client/client.py
> +        return response.choices[0].message.model_dump()['tool_calls'][0]['function']['arguments']
what does this do ?? Do we really need it ??

`.model_dump()['tool_calls'][0]['function']['arguments']`

2024-04-12 21:23 UTC, Taycode commented on server/openai_client/schemas.py
> +class SearchFields(BaseModel):
This is great but are we using it anywhere ??

2024-04-12 21:23 UTC, Taycode commented on server/openai_client/client.py
> +                api_key=api_key # Ensure the setting name is correct
Was there a reason in particular this was changed ?

2024-04-13 06:42 UTC, TaslimOwolarafe commented on server/openai_client/client.py
> +                            #  "schema": SearchFields.model_json_schema()
Okay.

2024-04-13 06:43 UTC, TaslimOwolarafe commented on server/openai_client/client.py
> +        return response.choices[0].message.model_dump()['tool_calls'][0]['function']['arguments']
That's how the output of the function that returns the json is gotten.

2024-04-13 06:44 UTC, TaslimOwolarafe commented on server/openai_client/schemas.py
> +class SearchFields(BaseModel):
I was going to use that as an output schema if the function wasn't enough but i think i can remove it now.

2024-04-13 06:44 UTC, TaslimOwolarafe commented on server/openai_client/client.py
> +                api_key=api_key # Ensure the setting name is correct
Yeah, I wanted to use it in the shell and it was giving me issues.

2024-04-13 06:44 UTC, TaslimOwolarafe commented on server/openai_client/client.py
> +                api_key=api_key # Ensure the setting name is correct
I can change it back though.

2024-04-17 16:36 UTC, Taycode commented on server/openai_client/client.py
> +        return response.choices[0].message.model_dump()['tool_calls'][0]['function']['arguments']
wow, that's pretty heavy... we would look at it later.

2024-04-17 16:40 UTC, Taycode commented on server/openai_client/client.py
> +                            #  "schema": SearchFields.model_json_schema()
you are yet to remove it.

2024-04-17 16:40 UTC, Taycode commented on server/openai_client/schemas.py
> +tools = [
use a different variable name and make it all caps since its a constant.

2024-04-17 16:40 UTC, Taycode commented on server/openai_client/schemas.py
> +class SearchFields(BaseModel):
you can still wrap the output into this. Would be good.

2024-04-17 17:06 UTC, TaslimOwolarafe commented on server/openai_client/client.py
> +                            #  "schema": SearchFields.model_json_schema()
Oh, sorry.
I did that on a different branch.

2024-04-19 05:29 UTC, TaslimOwolarafe commented on server/openai_client/client.py
> +                            #  "schema": SearchFields.model_json_schema()
DONE.

2024-04-21 00:14 UTC, Taycode approved these changes

2024-04-21 00:15 UTC, merged